### PR TITLE
Add support for GHC 9.4.1

### PR DESCRIPTION
**Pull request by christiaanb**

### CODE REVIEW

**Comment by teto** [comment]
What is holding this ? I am using both of your branches (natnormalise too) thanks for your work.

**Comment by Mikolaj** [comment]
Oh yes, it would so great if you could release the remaining plugins (I know there are several of them, but I use knownnat and normalise).

**Comment by Mikolaj** [comment]
A thoroughly respectful ping. :)

**Comment by christiaanb** [comment]
Sorry, life stuff got in the way. I was originally waiting with releasing this because I was hoping for some changes in the GHG 9.4 branch; but it got released without those changes. Anyhow, I'll release soon.

**Comment by christiaanb** [comment]
Released as version 0.7.7: https://hackage.haskell.org/package/ghc-typelits-knownnat-0.7.7

**Pull request merged**
